const icon = {
	'催单客诉': 'cuidankesu',
	'暂停单': 'zantingdan',
	'已取消': 'yiquxiao',
	'全部工单': 'quanbudingdan',
	'我的日程': 'wodeyiban',
	'待预约': 'daiyuyue',
	'待打卡': 'daidaka',
	'待完工': 'daiwangong',
	'待处理': 'daichuli',
	'已处理': 'yichuli',
	'已完工': 'yiwangong',
	'待结算': 'daijiesuan',
	'已结算': 'yijiesuan',
	'配件申请': 'peijianshenqing',
	'我的待办':'wodedaiban',
	'我的已办': 'wodeyiban',
	'历史发起': 'wofaqide',
	'我的发起': 'wofaqide',
	'工单统计': 'gongdan',
	'待派单': 'daipaidan',
	'待办客诉': 'daibankesu',
	'收费标准': 'fuwubiaozhun',
	'产品百科': 'chanpinbaike',
	'操作指引': 'caozuozhiyin',
	'服务政策': 'fuwuzhengce',
	'故障自查': 'guzhangzijian',
	'在线考试': 'zaixiankaoshi',
	'论坛中心': 'luntanzhongxin',
	'状态说明': 'zhuangtaishuoming',
	'接单学习': '',
}

export default icon
